### ISSUE TITLE
Error with initial book lookup when one of width, height, thickness don't exist

### ISSUE THREAD

**Issue by caseyszilagyi** [ECE-458-Books/ece458books#175]
9781439187920 doesn't return the book

**Comment by hkder** [comment]
This issue might be addressed through PR #205. @caseyszilagyi could you check if it is still a bug?

**Comment by hkder** [comment]
I just tested it with the above isbn and it seems to be the keyerror where certain keys are not present with GoogleBooks API. PR #205 does solve this issue.
