### ISSUE TITLE
Make URLs specific to info being displayed

### ISSUE THREAD

**Issue by danielfeinblatt** [ECE-458-Books/ece458books#228]
Currently some of the URLs are mildly broken. For example, with the book detail view, the url should have the identifying info of the book in it (like its pk), but it just says book info URL. This means all book details have the same URL, meaning they aren't back traceable. Also, going to that link on your own just shows a blank page. This should be updated so that someone could paste in a URL to a specific book detail with its identifier and that book detail would show up.

**Comment by caseyszilagyi** [comment]
This will also require loading the data using API calls from the detail pages, instead of passing them in through the useLocation() hook
