### ISSUE TITLE
The Edit-editable toggle is bad

### ISSUE THREAD

**Issue by danielfeinblatt** [ECE-458-Books/ece458books#230]
The edit-editable toggle doesn't really make much sense and is confusing. After clicking to edit something, the user should have two possible options from there: either cancel the edit and return back to the current information, or commit the edit (i.e. make the change). There shouldn't be this in beteween state where a person can edit and then do nothing. So, on edit, show a cancel and a save button. Also, this editable toggle shouldn't just be a plain button. But really should just get rid of this anyway.

**Comment by nex-pixel** [comment]
Book detail is done others can be simply updated from here.
