### ISSUE TITLE
SR selecting a book defaults the unit price to the one stored in the database (autofill)

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#322]
When Going to Create a new Line item in Sales Reconciliation after a Book is selected through name Search or ISBN search (depends on what we decide), the Unit Price is automatically filled with the one stored in the system for that book. This is still editable, its just the initial fill.

**Comment by caseyszilagyi** [comment]
Already have an issue for this in the current evolution
