### ISSUE TITLE
PO selecting a book defaults the unit price to the one stored in the database (autofill)

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#323]
When Going to Create a new Line item in Purchase Order after a Book is selected through name Search or ISBN search (depends on what we decide), the Wholesale Price is automatically filled with the one stored in the system for that book. This is still editable, its just the initial fill.

**Comment by caseyszilagyi** [comment]
This is not a requirement for purchase orders, only for sales reconciliations
