### ISSUE TITLE
On Book Detail page fix image upload and submit button's type

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#396]
![Screenshot 2023-02-27 at 3 32 18 PM](https://user-images.githubusercontent.com/72453378/221678940-103a661f-e8e9-4e80-bf06-55bd6cc5e270.png)

**Comment by nex-pixel** [comment]
All buttons to submit on this page have type="buton". Don't know why this is a problem.

**Comment by nex-pixel** [comment]
In the ConfirmPopup component, the submit button is the button that shows up in the popup, The state for that may be a button with no attribute type set for it. This may be an internal formik confimpopup situation.

**Comment by caseyszilagyi** [comment]
I have no idea how to fix this, but it doesn't break anything so I'm just going to close it. Doesn't seem very important
