### ISSUE TITLE
Sorting does not work for last_month_sales and best_buyback_rate

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#413]
The fields are not sortable. tested on postman and putting in - or + last_month_sales or best_buyback_rate doesn't do anything currently.

**Comment by danielfeinblatt** [comment]
@hkder Wondering if you can do this easier than I can, since u previously implemented ability to sort by serializermethodfields. If not, I can attempt to do it. Too tired tonight

**Comment by hkder** [comment]
Yeah working on this now. Had a paper to write today..
