### ISSUE TITLE
Default Image doesn't load for a couple of books detail view (check desciption)

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#427]

**Comment by nex-pixel** [comment]
![Image](https://user-images.githubusercontent.com/72453378/221984044-d8b84668-9f9c-4018-966d-8c3f451d8f53.png)

Go to these check the network request the url isn't being sent to frontend. So image doesn't showup. Maybe from earlier breaking of code.

**Comment by caseyszilagyi** [comment]
Going to leave open for now, but I don't think this is an issue. I think there is just no URL stored for this book, but we should be able to default on the frontend

**Comment by hkder** [comment]
I will look into it after feature for book list sorting is done.
