### ISSUE TITLE
Refresh Token Functionality on Frontend

### ISSUE THREAD

**Issue by hkder** [ECE-458-Books/ece458books#593]

**Comment by caseyszilagyi** [comment]
This includes a few things:

On logout, the backend needs to be called to invalidate the refresh token

On an unsuccessful request, the refresh token endpoint needs to be hit, then the new access token needs to be used to retry the request

If the access token life is changed, the check in /util/auth/CheckLoginStatus.tsx on the frontend will need to be updated
