### ISSUE TITLE
Reloading the site sometimes leaves the screen blank

### ISSUE THREAD

**Issue by nex-pixel** [ECE-458-Books/ece458books#604]
The accesstoken and userID is present in local storage, but the screen is blank. This happens directly after hot-relaoding with changes.

**Comment by hkder** [comment]
I actually had the same issue

**Comment by caseyszilagyi** [comment]
I've never noticed this, but if you guys could get some more information next time it happens that would be great (important things would be time since last login, page it happened on, whether this was the first page you had accessed in a while or it just happened randomly while using the site)

**Comment by caseyszilagyi** [comment]
Closing because there is not enough information to do any useful debugging. If anyone gets more information feel free to create a new ticket
